projects/urls.py
from django.urls import path
from projects.views import (index, ProjectListView,
                            ProjectDetailView, TaskListView,
                            TaskDetailView, WorkerListView,
                            WorkerDetailView, TaskTypeListView,
                            PositionListView, TaskTypeCreateView,
                            PositionCreateView, TaskTypeUpdateView,
                            PositionUpdateView, TaskTypeDeleteView,
                            PositionDeleteView, ProjectCreateView,
                            ProjectUpdateView, ProjectDeleteView,
                            WorkerCreateView, WorkerUpdateView,
                            WorkerDeleteView, TaskCreateView,
                            TaskDeleteView, TaskUpdateView,
                            toggle_assign_to_task)

urlpatterns = [
    path("", index, name="index"),
    path(
        "projects/",
        ProjectListView.as_view(),
        name="project-list"),
    path("projects/<int:pk>/",
         ProjectDetailView.as_view(),
         name="project-detail"),
    path(
        "tasks/",
        TaskListView.as_view(),
        name="task-list"),
    path("tasks/<int:pk>/", TaskDetailView.as_view(), name="task-detail"),
    path(
        "tasks/<int:pk>/toggle-assign/",
        toggle_assign_to_task,
        name="toggle-task-assign",
    ),
    path("workers/", WorkerListView.as_view(), name="worker-list"),
    path("workers/<int:pk>/",
         WorkerDetailView.as_view(),
         name="worker-detail"),
    path("tasks/tasktypes/",
         TaskTypeListView.as_view(),
         name="tasktype-list"),
    path("tasks/tasktypes/create/",
         TaskTypeCreateView.as_view(),
         name="tasktype-create"),
    path("tasks/tasktypes/update/<int:pk>",
         TaskTypeUpdateView.as_view(),
         name="tasktype-update"),
    path("tasks/tasktypes/delete/<int:pk>",
         TaskTypeDeleteView.as_view(),
         name="tasktype-delete"),
    path("workers/positions/",
         PositionListView.as_view(),
         name="position-list"),
    path("workers/positions/create/",
         PositionCreateView.as_view(),
         name="position-create"),
    path("workers/positions/update/<int:pk>",
         PositionUpdateView.as_view(),
         name="position-update"),
    path("workers/positions/delete/<int:pk>",
         PositionDeleteView.as_view(),
         name="position-delete"),
    path("projects/create/",
         ProjectCreateView.as_view(),
         name="project-create"),
    path("projects/update/<int:pk>",
         ProjectUpdateView.as_view(),
         name="project-update"),
    path("projects/delete/<int:pk>",
         ProjectDeleteView.as_view(),
         name="project-delete"),
    path("workers/create/", WorkerCreateView.as_view(), name="worker-create"),
    path("workers/<int:pk>/update/",
         WorkerUpdateView.as_view(),
         name="worker-update"),
    path("workers/<int:pk>/delete/",
         WorkerDeleteView.as_view(),
         name="worker-delete"),
    path("tasks/create/", TaskCreateView.as_view(), name="task-create"),
    path("tasks/<int:pk>/delete/",
         TaskDeleteView.as_view(),
         name="task-delete"),
    path("tasks/<int:pk>/update/",
         TaskUpdateView.as_view(),
         name="task-update")

]

app_name = "projects"

task_manager/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("projects.urls", namespace="projects")),
    path("accounts/", include("django.contrib.auth.urls"))
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

projects/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

from task_manager import settings


class TaskType(models.Model):
    name = models.CharField(max_length=64, unique=True)

    class Meta:
        ordering = ("name", )

    def __str__(self):
        return self.name


class Position(models.Model):
    name = models.CharField(max_length=64, unique=True)

    class Meta:
        ordering = ("name",)

    def __str__(self):
        return self.name


class Worker(AbstractUser):
    position = models.ForeignKey(Position,
                                 on_delete=models.PROTECT,
                                 related_name="workers")

    class Meta:
        ordering = ("username",)

    def __str__(self) -> str:
        return f"{self.username} ({self.first_name} {self.last_name})"


class Project(models.Model):
    name = models.CharField(max_length=255, unique=True, null=True)
    description = models.TextField()
    workers = models.ManyToManyField(settings.AUTH_USER_MODEL,
                                     related_name="projects")

    class Meta:
        ordering = ("name",)

    def __str__(self):
        return self.name


class Task(models.Model):
    PRIORITY_CHOICES = [
        ("urgent", "Urgent"),
        ("high", "High"),
        ("middle", "Middle"),
        ("low", "Low"),
    ]
    name = models.CharField(max_length=255)
    description = models.TextField()
    deadline = models.DateTimeField()
    is_completed = models.BooleanField(default=False)
    priority = models.CharField(max_length=20,
                                choices=PRIORITY_CHOICES)
    task_type = models.ForeignKey(TaskType,
                                  on_delete=models.PROTECT,
                                  related_name="tasks")
    project = models.ForeignKey(Project,
                                on_delete=models.CASCADE,
                                related_name="tasks")
    workers = models.ManyToManyField(settings.AUTH_USER_MODEL,
                                     related_name="tasks")

    class Meta:
        ordering = ("is_completed", "deadline", "priority")

    def __str__(self):
        return self.name

projects/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm
from django.core.exceptions import ValidationError
from django.utils import timezone

from projects.models import Worker, Task


class WorkerCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = Worker
        fields = UserCreationForm.Meta.fields + ("first_name",
                                                 "last_name",
                                                 "position",)


class WorkerUpdateForm(forms.ModelForm):
    class Meta(UserCreationForm.Meta):
        model = Worker
        fields = UserCreationForm.Meta.fields + ("first_name",
                                                 "last_name",
                                                 "position",)


class TaskCreateForm(forms.ModelForm):
    workers = forms.ModelMultipleChoiceField(
        queryset=get_user_model().objects.all(),
        widget=forms.CheckboxSelectMultiple,
    )

    class Meta:
        model = Task
        fields = ["name", "description", "deadline", "is_completed",
                  "priority", "task_type", "project", "workers"]
        widgets = {
            "deadline": forms.DateTimeInput(attrs={"type": "datetime-local"}),
        }

    def clean_deadline(self):
        return validate_deadline(self.cleaned_data["deadline"])


class TaskUpdateForm(forms.ModelForm):
    workers = forms.ModelMultipleChoiceField(
        queryset=get_user_model().objects.all(),
        widget=forms.CheckboxSelectMultiple,
    )

    class Meta:
        model = Task
        fields = ["name", "description", "deadline", "is_completed",
                  "priority", "task_type", "project", "workers"]
        widgets = {
            "deadline": forms.DateTimeInput(attrs={"type": "datetime-local"}),
        }

    def clean_deadline(self):
        return validate_deadline(self.cleaned_data["deadline"])


def validate_deadline(deadline):
    if deadline <= timezone.now():
        raise ValidationError("The deadline must be a future date.")
    return deadline


class TaskSearchForm(forms.Form):
    name = forms.CharField(max_length=255,
                           required=False,
                           label="",
                           widget=forms.TextInput(
                               attrs={
                                   "placeholder": "Search by name"}))


class ProjectSearchForm(forms.Form):
    name = forms.CharField(
        max_length=64,
        required=False,
        label="",
        widget=forms.TextInput(
            attrs={"placeholder": "Search by name"}
        )
    )

projects/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse_lazy
from django.utils import timezone
from django.views import generic

from projects.forms import (WorkerCreationForm,
                            WorkerUpdateForm,
                            TaskCreateForm,
                            TaskUpdateForm, ProjectSearchForm, TaskSearchForm)
from projects.models import Project, Task, Worker, TaskType, Position


def index(request):
    """View function for the home page of the site."""
    return render(request, "projects/index.html")


class ProjectListView(LoginRequiredMixin, generic.ListView):
    model = Project
    paginate_by = 8

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(ProjectListView, self).get_context_data(**kwargs)
        name = self.request.GET.get("name", "")
        context["search_form"] = ProjectSearchForm(
            initial={"name": name}
        )
        return context

    def get_queryset(self):
        queryset = Project.objects.all()
        form = ProjectSearchForm(self.request.GET)
        if form.is_valid():
            return queryset.filter(name__icontains=form.cleaned_data["name"])
        return queryset


class ProjectDetailView(LoginRequiredMixin, generic.DetailView):
    model = Project
    queryset = Project.objects.prefetch_related("tasks", "tasks__workers")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        project = self.object
        context["active_tasks"] = (project.tasks.
                                   filter(is_completed=False).count())
        context["percent_of_finished_task"] = round(
            project.tasks.filter(is_completed=True).
            count() / project.tasks.count() * 100)
        return context


class TaskListView(LoginRequiredMixin, generic.ListView):
    model = Project
    paginate_by = 15
    queryset = Task.objects.select_related("task_type", "project")

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(TaskListView, self).get_context_data(**kwargs)
        name = self.request.GET.get("name", "")
        context["search_form"] = TaskSearchForm(
            initial={"name": name}
        )
        return context

    def get_queryset(self):
        queryset = Task.objects.all()
        form = TaskSearchForm(self.request.GET)
        if form.is_valid():
            return queryset.filter(name__icontains=form.cleaned_data["name"])
        return queryset


class TaskDetailView(LoginRequiredMixin, generic.DetailView):
    model = Task


class WorkerListView(LoginRequiredMixin, generic.ListView):
    model = Worker
    paginate_by = 15
    queryset = Worker.objects.select_related("position")


class WorkerDetailView(LoginRequiredMixin, generic.DetailView):
    model = Worker
    queryset = Worker.objects.prefetch_related("projects", "tasks")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        worker = self.object
        context["overdue_tasks"] = (worker.tasks.
                                    filter(is_completed=False,
                                           deadline__lt=timezone.now()).count())
        return context


class TaskTypeListView(LoginRequiredMixin, generic.ListView):
    model = TaskType
    paginate_by = 15


class PositionListView(LoginRequiredMixin, generic.ListView):
    model = Position
    paginate_by = 15


class TaskTypeCreateView(LoginRequiredMixin, generic.CreateView):
    model = TaskType
    fields = "__all__"
    success_url = reverse_lazy("projects:tasktype-list")


class TaskTypeUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = TaskType
    fields = "__all__"
    success_url = reverse_lazy("projects:tasktype-list")


class TaskTypeDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = TaskType
    success_url = reverse_lazy("projects:tasktype-list")


class PositionCreateView(LoginRequiredMixin, generic.CreateView):
    model = Position
    fields = "__all__"
    success_url = reverse_lazy("projects:position-list")


class PositionUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Position
    fields = "__all__"
    success_url = reverse_lazy("projects:position-list")


class PositionDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Position
    success_url = reverse_lazy("projects:position-list")


class ProjectCreateView(LoginRequiredMixin, generic.CreateView):
    model = Project
    fields = "__all__"
    success_url = reverse_lazy("projects:project-list")


class ProjectUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Project
    fields = "__all__"
    success_url = reverse_lazy("projects:project-list")


class ProjectDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Project
    success_url = reverse_lazy("projects:project-list")


class WorkerCreateView(LoginRequiredMixin, generic.CreateView):
    model = Worker
    form_class = WorkerCreationForm
    success_url = reverse_lazy("projects:worker-list")


class WorkerUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Worker
    form_class = WorkerUpdateForm
    success_url = reverse_lazy("projects:worker-list")


class WorkerDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Worker
    success_url = reverse_lazy("projects:worker-list")


class TaskCreateView(LoginRequiredMixin, generic.CreateView):
    model = Task
    form_class = TaskCreateForm
    success_url = reverse_lazy("projects:task-list")


class TaskUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Task
    form_class = TaskUpdateForm
    success_url = reverse_lazy("projects:task-list")


class TaskDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Task
    success_url = reverse_lazy("projects:task-list")


@login_required
def toggle_assign_to_task(request, pk):
    worker = Worker.objects.get(id=request.user.id)
    if (
        Task.objects.get(id=pk) in worker.tasks.all()
    ):
        worker.tasks.remove(pk)
    else:
        worker.tasks.add(pk)
    return HttpResponseRedirect(reverse_lazy(
        "projects:task-detail",
        args=[pk]
    ))

templates/projects/position_confirm_delete.html
{% extends 'layouts/base-presentation.html' %}
{% block content %}
{% load crispy_forms_filters %}
<header>
    <div class="container">
      <div class="row">
        <div class="row text-center my-sm-5 mt-5">
          <div class="col-lg-7 mx-auto my-sm-5 mt-5">
            <div class="card d-flex blur justify-content-center p-4 shadow-lg my-sm-0 my-sm-6 mt-8 mb-5">
              <div class="text-center">
                <h1>Delete position
    <a type="button" class="btn bg-gradient-primary w-auto me-1 mb-0" href="{% url 'projects:position-list' %}"> ⨉</a></h1>
  <p>Are you sure you want to delete the position {{ position.name }}?</p>
  <form action="" method="post">
    {% csrf_token %}
    <input type="submit" value="Yes, delete" class="btn btn-outline-primary mb-0"></form>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </header>
{% endblock %}

templates/projects/position_form.html
{% extends 'layouts/base-presentation.html' %}
{% block content %}
{% load crispy_forms_filters %}
<header>
    <div class="container">
      <div class="row">
        <div class="row text-center my-sm-5 mt-5">
          <div class="col-lg-7 mx-auto my-sm-5 mt-5">
            <div class="card d-flex blur justify-content-center p-4 shadow-lg my-sm-0 my-sm-6 mt-8 mb-5">
              <div class="text-center">
                <h1>{{ object|yesno:"Update,Create" }} position</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}

    <input type="submit" value="Submit" class="btn btn-primary">
  </form>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </header>
{% endblock %}

templates/projects/position_list.html
{% extends 'layouts/base-presentation.html' %}
{% block body_class %} position-list {% endblock body_class %}
{% block content %}
  <header>
    <div class="page-header section-height-85">
      <div>
        <img class="position-absolute fixed-top ms-auto w-50 h-100 z-index-0 d-none d-sm-none d-md-block border-radius-section border-top-end-radius-0 border-top-start-radius-0 border-bottom-end-radius-0" src="{{ ASSETS_ROOT }}/img/curved-images/curved8.jpg">
      </div>
      <div class="container">
        <div class="row">
          <div class="col-lg-7 d-flex justify-content-center flex-column">
            <div class="card d-flex blur justify-content-center p-4 shadow-lg my-sm-0 my-sm-6 mt-8 mb-5">
              <div class="text-center">
                <h3 class="text-gradient text-primary">Position list
    <a href="{% url 'projects:position-create' %}" >+</a></h3>
                {% if position_list %}
    <table class="table">
      <tr>
        <th>id</th>
        <th>name</th>
        <th>Update</th>
        <th>Delete</th>
      </tr>
    <ul>
      {% for position in position_list %}
          <tr>
            <td>{{ position.id }}</td>
            <td>{{ position.name }}</td>
            <td><a href="{% url 'projects:position-update' pk=position.id %}" class="btn btn-primary ">Update</a></td>
            <td><a href="{% url 'projects:position-delete' pk=position.id %}" class="btn btn-primary">Delete</a></td>
          </tr>
      {% endfor %}
    </ul>
    </table>

  {% else %}
    <p>There are no positions</p>
  {% endif %}
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </header>
{% endblock %}

templates/projects/project_confirm_delete.html
{% extends 'layouts/base-presentation.html' %}
{% block content %}
{% load crispy_forms_filters %}
<header>
    <div class="container">
      <div class="row">
        <div class="row text-center my-sm-5 mt-5">
          <div class="col-lg-8 mx-auto my-sm-5 mt-5">
            <div class="card blur p-4 shadow-lg my-sm-0 my-sm-6 mt-8 mb-5">
              <div class="text-center">
                <h1>Delete project
    <a type="button" class="btn bg-gradient-primary w-auto me-1 mb-0" href="{% url 'projects:project-list' %}">Cancel</a></h1>
  <p>Are you sure you want to delete the project {{ project.name }}?</p>
  <p>All project's tasks will be deleted</p>
  <form action="" method="post">
    {% csrf_token %}
    <input type="submit" value="Yes, delete" class="btn btn-outline-primary mb-0"></form>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </header>
{% endblock %}

templates/projects/project_detail.html
{% extends 'layouts/base-presentation.html' %}

{% block content %}
  <section class="py-sm-7 py-5 position-relative">
    <div class="container">
      <div class="row">
        <div class="col-12 mx-auto">
          <div class="row py-lg-7 py-5">
            <div class="col-lg-3 col-md-5 position-relative my-auto">
              <img class="img border-radius-lg max-width-200 w-100 position-relative z-index-2" src="https://miro.medium.com/v2/resize:fit:1400/1*8ygFKYb0Yo6Hc-vnScGA9A.png">
            </div>
            <div class="col-lg-7 col-md-7 z-index-2 position-relative px-md-2 px-sm-5 mt-sm-0 mt-4">
              <div class="d-flex justify-content-between align-items-center mb-2">
                <h4 class="mb-0">{{ project.name }}</h4>
                <div class="d-block"><a href="{% url 'projects:project-update' pk=project.id %}" class="btn btn-outline-secondary mb-0">
      Update</a>
                  <a href="{% url 'projects:project-delete' pk=project.id %}" class="btn btn-outline-primary mb-0">
      Delete</a>
                </div>
              </div>
              <h6>Description: </h6>
              <p class="text-lg mb-0">
                {{ project.description }}
              </p>
              <h6>Workers:</h6>
    <ul>
        {% for worker in project.workers.all %}
            <li>{{ worker.username }} ({{ worker.first_name }} {{ worker.last_name }})</li>
        {% endfor %}
    </ul>
            <button type="button" class="btn btn-sm btn-outline-info  mb-0">
               This project have {{ active_tasks }} active tasks</button>
            <button type="button" class="btn btn-sm btn-outline-info  mb-0">
               You have already finished {{ percent_of_finished_task }}% of tasks</button>
            <h6>
    Current tasks:</h6>

    {% with tasks=project.tasks.all %}
    {% if tasks %}
        <ul>
            {% for task in tasks %}
                {% if not task.is_completed %}
                    <li>{% if user in task.workers.all %}🚀{% endif %}{{ task.name }} ({{ task.deadline }})</li>
                {% endif %}
            {% endfor %}
        </ul>
    {% else %}
        <p>You have already finished all the task!</p>
    {% endif %}
{% endwith %}
            </div>
          </div>
        </div>
      </div>
    </div></section>
{% endblock %}

templates/projects/project_form.html
{% extends 'layouts/base-presentation.html' %}
{% block content %}
{% load crispy_forms_filters %}
<header>
    <div class="container">
      <div class="row">
        <div class="row text-center my-sm-5 mt-5">
          <div class="col-lg-7 mx-auto my-sm-5 mt-5">
            <div class="card d-flex blur justify-content-center p-4 shadow-lg my-sm-0 my-sm-6 mt-8 mb-5">
              <div class="text-center">
                 <h1>{{ object|yesno:"Update,Create" }} project</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}

    <input type="submit" value="Submit" class="btn btn-primary">
  </form>

              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </header>
{% endblock %}

templates/projects/project_list.html
{% extends 'layouts/base-presentation.html' %}
{% load crispy_forms_filters %}

{% block content %}
  <div class="container mt-8">
  <h1>
    Project list
    <a href="{% url 'projects:project-create' %}" class="btn btn-primary link-to-page">+</a>
  </h1>
  <form method="get" action="" class="form-inline d-flex align-items-center">
      {{ search_form|crispy }}
      <input class="btn btn-secondary" type="submit" value="🔍">
  </form>
  {% if project_list %}
    <div class="row">
      {% for project in project_list %}
        {% if request.user in project.workers.all %}
        <div class="col-lg-3 col-sm-6">
          <div class="card card-plain card-blog">
            <div class="card-body px-0">
              <h5>
                <a href="javascript:;" class="text-dark font-weight-bold">{{ project.name }}</a>
              </h5>
              <p>
                {{ project.description }}
              </p>
              <a href="{% url "projects:project-detail" pk=project.id %}" class="text-info icon-move-right">Read More
                <i class="fas fa-arrow-right text-sm"></i>
              </a>
            </div>
          </div>
        </div>
          {% endif %}
      {% endfor %}</div>
  {% else %}
    <p>There are not your projects</p>
  {% endif %}</div>
{% endblock %}

templates/projects/task_form.html
{% extends 'layouts/base-presentation.html' %}
{% block content %}
{% load crispy_forms_filters %}
<header>
    <div class="container">
      <div class="row">
        <div class="row text-center my-sm-5 mt-5">
          <div class="col-lg-7 mx-auto my-sm-5 mt-5">
            <div class="card d-flex blur justify-content-center p-4 shadow-lg my-sm-0 my-sm-6 mt-8 mb-5">
              <div class="text-center">
                 <h1>{{ object|yesno:"Update,Create" }} task</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}

    <input type="submit" value="Submit" class="btn btn-primary">
  </form>

              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </header>
{% endblock %}

templates/projects/tasktype_list.html
{% extends 'layouts/base-presentation.html' %}
{% block body_class %} position-list {% endblock body_class %}
{% block content %}
  <header>
    <div class="page-header section-height-85">
      <div>
        <img class="position-absolute fixed-top ms-auto w-50 h-100 z-index-0 d-none d-sm-none d-md-block border-radius-section border-top-end-radius-0 border-top-start-radius-0 border-bottom-end-radius-0" src="{{ ASSETS_ROOT }}/img/curved-images/curved8.jpg">
      </div>
      <div class="container">
        <div class="row">
          <div class="col-lg-7 d-flex justify-content-center flex-column">
            <div class="card d-flex blur justify-content-center p-4 shadow-lg my-sm-0 my-sm-6 mt-8 mb-5">
              <div class="text-center">
                <h3 class="text-gradient text-primary">Task type list
    <a href="{% url 'projects:tasktype-create' %}" >+</a></h3>
  {% if tasktype_list %}
    <table class="table">
      <tr>
        <th>id</th>
        <th>name</th>
        <th>update</th>
        <th>delete</th>
      </tr>
    <ul>
      {% for tasktype in tasktype_list %}
          <tr>
            <td>{{ tasktype.id }}</td>
            <td>{{ tasktype.name }}</td>
            <td><a href="{% url 'projects:tasktype-update' pk=tasktype.id %}" class="btn btn-primary ">update</a></td>
            <td><a href="{% url 'projects:tasktype-delete' pk=tasktype.id %}" class="btn btn-primary ">Delete</a></td>
          </tr>
      {% endfor %}
    </ul>
    </table>

  {% else %}
    <p>There are no task types</p>
  {% endif %}</div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </header>

{% endblock %}

templates/projects/worker_detail.html
{% extends 'layouts/base-presentation.html' %}
{% block body_class %} position-list {% endblock body_class %}
{% block content %}
  <header>
    <div class="page-header section-height-85">
      <div class="container">
        <div class="row">
          <div class="col-lg-7 d-flex justify-content-center flex-column">
            <div class="card d-flex blur justify-content-center p-4 shadow-lg my-sm-0 my-sm-6 mt-8 mb-5">
              <div>
                <h3 class="text-gradient text-primary">{{ worker.username }}   ({{ worker.first_name }} {{ worker.last_name }})</h3>
                <a href="{% url 'projects:worker-update' pk=worker.id%}" class="btn btn-outline-secondary mb-0">Update</a>
                <a href="{% url 'projects:worker-delete' pk=worker.id %}" class="btn btn-outline-primary mb-0">Delete</a>


  </h1>
  <p>Position: ({{ worker.position }})</p>
  <p>Email: {{ worker.email }}</p>
  <h1>
    Projects:</h1>

    <ul>
        {% for project in worker.projects.all %}
            <li>{{ project.name }}</li>
        {% endfor %}
    </ul>
             {% if overdue_tasks > 0 %}
                <button type="button" class="btn btn-outline-danger btn-sm me-2">{{ overdue_tasks }} overdue tasks</button>
              {% else %}
               <button type="button" class="btn btn-outline-success btn-sm me-2">{{ overdue_tasks }} overdue tasks</button>
              {% endif %}

  <h1>
    Current tasks:</h1>

    {% with tasks=worker.tasks.all %}
    {% if tasks %}
        <ul>
            {% for task in tasks %}
                {% if not task.is_completed %}
                  <a type="button" class="btn btn-outline-primar btn-sm me-2" href="{% url "projects:task-detail" pk=task.id %}">{{ task.name }} ({{ task.deadline }})</a>
                {% endif %}
            {% endfor %}
        </ul>
    {% else %}
        <p>You have already finished all the task!</p>
    {% endif %}
{% endwith %}

              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </header>
{% endblock %}

templates/projects/worker_list.html
{% extends 'layouts/base-presentation.html' %}

{% block content %}
  <div class="container mt-8">
  <h1>
    Worker list
    <a href="{% url 'projects:worker-create' %}" class="btn btn-primary link-to-page">
      Create
    </a> <a href="{% url 'projects:position-list' %}" class="btn btn-primary link-to-page">
      Check all the positions
    </a>
  </h1>
  {% if worker_list %}
    <table class="table">
      <tr>
        <th>ID</th>
        <th>Username</th>
        <th>Full name</th>
        <th>Position</th>
        <th>Email</th>
      </tr>
    <ul>
      {% for worker in worker_list %}
          <tr>
            <td><a type="button" class="btn btn-outline-primar btn-sm me-2" href="{% url "projects:worker-detail" pk=worker.id %}">{{ worker.id }}</a></td>
            <td>{% if user == worker %}🚀{% endif %}{{ worker.username }}</td>
            <td>{{ worker.first_name}} {{ worker.last_name }}</td>
            <td>{{ worker.position }}</td>
            <td>{{ worker.email }}</td>
          </tr>
      {% endfor %}
    </ul></table>

  {% else %}
    <p>There are no workers</p>
  {% endif %}</div>
{% endblock %}