projects/urls.py
from django.urls import path
from projects.views import (index, ProjectListView,
                            ProjectDetailView, TaskListView,
                            TaskDetailView, WorkerListView,
                            WorkerDetailView, TaskTypeListView,
                            PositionListView, TaskTypeCreateView,
                            PositionCreateView, TaskTypeUpdateView,
                            PositionUpdateView, TaskTypeDeleteView,
                            PositionDeleteView, ProjectCreateView,
                            ProjectUpdateView, ProjectDeleteView,
                            WorkerCreateView, WorkerUpdateView,
                            WorkerDeleteView, TaskCreateView,
                            TaskDeleteView, TaskUpdateView,
                            toggle_assign_to_task)

urlpatterns = [
    path("", index, name="index"),
    path(
        "projects/",
        ProjectListView.as_view(),
        name="project-list"),
    path("projects/<int:pk>/",
         ProjectDetailView.as_view(),
         name="project-detail"),
    path(
        "tasks/",
        TaskListView.as_view(),
        name="task-list"),
    path("tasks/<int:pk>/", TaskDetailView.as_view(), name="task-detail"),
    path(
        "tasks/<int:pk>/toggle-assign/",
        toggle_assign_to_task,
        name="toggle-task-assign",
    ),
    path("workers/", WorkerListView.as_view(), name="worker-list"),
    path("workers/<int:pk>/",
         WorkerDetailView.as_view(),
         name="worker-detail"),
    path("tasks/tasktypes/",
         TaskTypeListView.as_view(),
         name="tasktype-list"),
    path("tasks/tasktypes/create/",
         TaskTypeCreateView.as_view(),
         name="tasktype-create"),
    path("tasks/tasktypes/update/<int:pk>",
         TaskTypeUpdateView.as_view(),
         name="tasktype-update"),
    path("tasks/tasktypes/delete/<int:pk>",
         TaskTypeDeleteView.as_view(),
         name="tasktype-delete"),
    path("workers/positions/",
         PositionListView.as_view(),
         name="position-list"),
    path("workers/positions/create/",
         PositionCreateView.as_view(),
         name="position-create"),
    path("workers/positions/update/<int:pk>",
         PositionUpdateView.as_view(),
         name="position-update"),
    path("workers/positions/delete/<int:pk>",
         PositionDeleteView.as_view(),
         name="position-delete"),
    path("projects/create/",
         ProjectCreateView.as_view(),
         name="project-create"),
    path("projects/update/<int:pk>",
         ProjectUpdateView.as_view(),
         name="project-update"),
    path("projects/delete/<int:pk>",
         ProjectDeleteView.as_view(),
         name="project-delete"),
    path("workers/create/", WorkerCreateView.as_view(), name="worker-create"),
    path("workers/<int:pk>/update/",
         WorkerUpdateView.as_view(),
         name="worker-update"),
    path("workers/<int:pk>/delete/",
         WorkerDeleteView.as_view(),
         name="worker-delete"),
    path("tasks/create/", TaskCreateView.as_view(), name="task-create"),
    path("tasks/<int:pk>/delete/",
         TaskDeleteView.as_view(),
         name="task-delete"),
    path("tasks/<int:pk>/update/",
         TaskUpdateView.as_view(),
         name="task-update")

]

app_name = "projects"

task_manager/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("projects.urls", namespace="projects")),
    path("accounts/", include("django.contrib.auth.urls"))
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/includes/footer.html
  <footer class="footer pt-5 mt-5">
        <div class="col-12">
          <div class="text-center">
            <p class="my-4 text-sm">
              Task Flow System by &copy; <a target="_blank" href="https://bit.ly/3fKQZaL" target="_blank">Valeriia Shvanska</a>
            </p>
          </div>
        </div>
  </footer>

templates/includes/navigation.html
  <div class="container position-sticky z-index-sticky top-0">
    <div class="row">
      <div class="col-12">
        <nav class="navbar navbar-expand-lg  blur blur-rounded top-0 z-index-fixed shadow position-absolute my-3 py-2 start-0 end-0 mx-4">
          <div class="container-fluid">
            <a class="navbar-brand font-weight-bolder ms-sm-3" 
               href="{% url 'projects:index' %}" rel="tooltip" title="Designed and Coded by Creative Tim" data-placement="bottom">
              Task Flow System
            </a>
            <a class="navbar-brand font-weight-bolder ms-sm-3"
               href="{% url 'projects:project-list' %}" rel="tooltip" title="Designed and Coded by Creative Tim" data-placement="bottom">
              Projects
            </a>
            <a class="navbar-brand font-weight-bolder ms-sm-3"
               href="{% url 'projects:task-list' %}" rel="tooltip" title="Designed and Coded by Creative Tim" data-placement="bottom">
              Tasks
            </a>
            <a class="navbar-brand font-weight-bolder ms-sm-3"
               href="{% url 'projects:worker-list' %}" rel="tooltip" title="Designed and Coded by Creative Tim" data-placement="bottom">
              Workers
            </a>
            {% if user.is_authenticated %}
              <a class="nav-link nav-link-icon me-2" href="{% url 'logout' %}?next={{request.path}}">
              <i class="fa fa-sign-out me-1"></i>
              <p class="d-inline text-sm z-index-1 font-weight-bold" data-bs-toggle="tooltip" data-bs-placement="bottom" title="Logout">Logout</p>
            </a>
            <a href="{{ user.get_absolute_url }}"
                     target="_blank"
                     class="btn btn-sm  bg-gradient-primary btn-round mb-0 me-1 mt-2 mt-md-0">{{ user.get_username }}</a>
              {% else %}
              <a class="nav-link nav-link-icon me-2" href="{% url 'login' %}?next={{request.path}}">
              <i class="fa fa-sign-out me-1"></i>
              <p class="d-inline text-sm z-index-1 font-weight-bold" data-bs-toggle="tooltip" data-bs-placement="bottom" title="Logout">Login</p>
            </a>
            {% endif %}
            </div>
        </nav>
        <!-- End Navbar -->
      </div>
    </div>
  </div>

templates/includes/pagination.html
{% load query_transform %}
{% if is_paginated %}
  <ul class="pagination">
  {% if page_obj.has_previous %}
    <li class="page-item"><a class="page-link" href="?{% query_transform request page=page_obj.previous_page_number %}"
    >Prev</a></li>
  {% endif %}
    <li class="page-item active"><span class = "page-link">{{ page_obj.number }}</span></li>
  {% if page_obj.has_next %}
    <li class="page-item"><a class="page-link" href="?{% query_transform request page=page_obj.next_page_number %}">
      Next</a></li>
  {% endif %}
  </ul>
{% endif %}

templates/includes/scripts.html
  <script src="{{ ASSETS_ROOT }}/js/core/popper.min.js" type="text/javascript"></script>
  <script src="{{ ASSETS_ROOT }}/js/core/bootstrap.min.js" type="text/javascript"></script>
  <script src="{{ ASSETS_ROOT }}/js/plugins/perfect-scrollbar.min.js"></script>
  <script src="{{ ASSETS_ROOT }}/js/plugins/prism.min.js"></script>
  <script src="{{ ASSETS_ROOT }}/js/plugins/parallax.min.js"></script>